# Dockerfile permettant d'exécuter les tests Swift Package
FROM swift:latest

# Set environment variables for all future commands and containers
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y locales && \
    sed -i 's/^# *\(en_GB.UTF-8 UTF-8\)/\1/' /etc/locale.gen && \
    locale-gen en_GB.UTF-8 && \
    update-locale LANG=en_GB.UTF-8 && \
    rm -rf /var/lib/apt/lists/*

ENV LANG=en_GB.UTF-8
ENV LANGUAGE=en_GB:en
ENV LC_ALL=en_GB.UTF-8

WORKDIR /package
COPY . .

RUN swift test --enable-swift-testing
# --parallel        