sonar.organization=auvents-brave
sonar.projectKey=auvents-brave_Stheno
sonar.projectName=Stheno
sonar.sourceEncoding=UTF-8
sonar.sources=Stheno/Sources
sonar.tests=Stheno/Tests
sonar.exclusions=**/.build/**,**/.swiftpm/**,**/DerivedData/**
sonar.test.inclusions=**/Tests/**
sonar.swift.coverage.reportPaths=coverage.xml
