sonar.organization=auvents-brave
sonar.projectKey=auvents-brave_Stheno
sonar.projectName=Stheno
sonar.sourceEncoding=UTF-8
sonar.sources=Sources
sonar.tests=Tests
sonar.exclusions=**/.build/**,**/.swiftpm/**,**/DerivedData/**
sonar.test.inclusions=Tests/**
sonar.coverageReportPaths=coverage.xml
