name: Apple iOS (iPad)
on: { push: { branches: [main] }, pull_request: {}, workflow_dispatch: {} }

permissions:
  contents: read

concurrency:
  group: ci-${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/_apple-sim-tests.yml
    with:
      workflow-name: "iPad"
      scheme: "Stheno"
      sim-runtime-prefix: "com.apple.CoreSimulator.SimRuntime.iOS"
      device-name-regex: "iPad"
