name: Apple Mac Catalyst
on: { push: { branches: [main] }, pull_request: {}, workflow_dispatch: {} }

concurrency:
  group: ci-${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test | xcode${{ matrix.xcode-version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode-version: "26.3"
            macos-runner: "macos-26"
          - xcode-version: "15"
            macos-runner: "macos-14"
    runs-on: ${{ matrix.macos-runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: "6.2.3"
          development: true
      - run: xcodebuild -resolvePackageDependencies -scheme "Stheno" -toolchain swift IDEPackageSupportToolchainOverrideForManifestLoading=swift
      - run: xcodebuild test -scheme "Stheno" -toolchain swift IDEPackageSupportToolchainOverrideForManifestLoading=swift -destination "platform=macOS,variant=Mac Catalyst"
