name: Build WASI
permissions:
  contents: read
on:
  workflow_dispatch:
  #push:
  #  branches:
  #pull_request:
  #  branches:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  build-wasi:
    name: WebAssembly
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev pkg-config

      - name: Ensure Swift 6.2 Toolchain (WASI)
        shell: bash
        run: |
          set -euo pipefail
          if command -v swift >/dev/null && swift --version | grep -q "6\.2"; then
            echo "Swift 6.2 already installed."
            exit 0
          fi

          echo "Swift 6.2 not found. Installing Swift WASI toolchain..."
          SWIFT_TARBALL_URL="https://download.swift.org/swift-6.2-release/wasm-wasi/swift-6.2-RELEASE/swift-6.2-RELEASE-wasm-wasi.tar.gz"
          curl -L "$SWIFT_TARBALL_URL" -o swift-toolchain.tar.gz
          tar -xzf swift-toolchain.tar.gz
          sudo rm -rf /usr/local/swift-6.2-RELEASE-wasm-wasi
          sudo mv swift-6.2-RELEASE-wasm-wasi /usr/local/swift-6.2-RELEASE-wasm-wasi
          rm -f swift-toolchain.tar.gz

          TOOLCHAIN_ROOT="/usr/local/swift-6.2-RELEASE-wasm-wasi"
          TOOLCHAIN_PATH="$TOOLCHAIN_ROOT/usr/bin"
          TOOLCHAIN_LIB="$TOOLCHAIN_ROOT/usr/lib/swift/linux"

          if [ ! -x "$TOOLCHAIN_PATH/swift" ]; then
            echo "Expected Swift binary not found at $TOOLCHAIN_PATH/swift" >&2
            exit 1
          fi

          echo "$TOOLCHAIN_PATH" >> "$GITHUB_PATH"
          if [ -n "${LD_LIBRARY_PATH:-}" ]; then
            echo "LD_LIBRARY_PATH=$TOOLCHAIN_LIB:${LD_LIBRARY_PATH}" >> "$GITHUB_ENV"
          else
            echo "LD_LIBRARY_PATH=$TOOLCHAIN_LIB" >> "$GITHUB_ENV"
          fi

      - name: Verify Swift 6.2
        shell: bash
        run: |
          set -euo pipefail
          TOOLCHAIN_ROOT="/usr/local/swift-6.2-RELEASE-wasm-wasi"
          TOOLCHAIN_PATH="$TOOLCHAIN_ROOT/usr/bin"
          TOOLCHAIN_LIB="$TOOLCHAIN_ROOT/usr/lib/swift/linux"
          if [ -d "$TOOLCHAIN_PATH" ]; then
            export PATH="$TOOLCHAIN_PATH:$PATH"
          fi
          if [ -d "$TOOLCHAIN_LIB" ]; then
            export LD_LIBRARY_PATH="$TOOLCHAIN_LIB:${LD_LIBRARY_PATH:-}"
          fi
          swift --version
          swift --version | grep -q "6\.2"

      - name: Build (WASI target)
        shell: bash
        run: |
          set -euo pipefail
          TOOLCHAIN_ROOT="/usr/local/swift-6.2-RELEASE-wasm-wasi"
          TOOLCHAIN_PATH="$TOOLCHAIN_ROOT/usr/bin"
          TOOLCHAIN_LIB="$TOOLCHAIN_ROOT/usr/lib/swift/linux"
          if [ -d "$TOOLCHAIN_PATH" ]; then
            export PATH="$TOOLCHAIN_PATH:$PATH"
          fi
          if [ -d "$TOOLCHAIN_LIB" ]; then
            export LD_LIBRARY_PATH="$TOOLCHAIN_LIB:${LD_LIBRARY_PATH:-}"
          fi
          swift build --triple wasm32-unknown-wasi
