name: Build Mac
permissions:
  contents: read
on:
  workflow_dispatch:
  #push:
  #  branches:
  #pull_request:
  #  branches:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  build-mac:
    name: Mac
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Swift 6.2 Toolchain
        shell: bash
        run: |
          set -euo pipefail
          if command -v swift >/dev/null && swift --version | grep -q "6\.2"; then
            echo "Swift 6.2 already installed."
            exit 0
          fi

          echo "Swift 6.2 not found. Installing Swift toolchain..."
          SWIFT_PKG_URL="https://download.swift.org/swift-6.2-release/xcode/swift-6.2-RELEASE/swift-6.2-RELEASE-osx.pkg"
          curl -L "$SWIFT_PKG_URL" -o swift-toolchain.pkg
          sudo installer -pkg swift-toolchain.pkg -target /
          rm -f swift-toolchain.pkg

          TOOLCHAIN_PATH="/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin"
          if [ ! -d "$TOOLCHAIN_PATH" ]; then
            echo "Expected toolchain path missing: $TOOLCHAIN_PATH" >&2
            exit 1
          fi

          echo "$TOOLCHAIN_PATH" >> "$GITHUB_PATH"
          export PATH="$TOOLCHAIN_PATH:$PATH"

      - name: Verify Swift 6.2
        shell: bash
        run: |
          set -euo pipefail
          TOOLCHAIN_PATH="/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin"
          if [ -d "$TOOLCHAIN_PATH" ]; then
            export PATH="$TOOLCHAIN_PATH:$PATH"
          fi
          swift --version
          swift --version | grep -q "6\.2"

      - name: Run Tests
        run: swift test
