name: Build WASI
permissions:
  contents: read
on:
  workflow_dispatch:
  #push:
  #  branches:
  #pull_request:
  #  branches:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  build-wasi:
    name: WebAssembly
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev pkg-config

      - name: Ensure Swift 6.2 Toolchain (WASI)
        shell: bash
        run: |
          set -euo pipefail
          if command -v swift >/dev/null && swift --version | grep -q "6\.2"; then
            echo "Swift 6.2 already installed."
            exit 0
          fi

          echo "Swift 6.2 not found. Installing Swift WASI toolchain..."
          SWIFT_TARBALL_URL="https://download.swift.org/swift-6.2-release/wasm-wasi/swift-6.2-RELEASE/swift-6.2-RELEASE-wasm-wasi.tar.gz"
          curl -L "$SWIFT_TARBALL_URL" -o swift-toolchain.tar.gz
          tar -xzf swift-toolchain.tar.gz
          sudo rm -rf /usr/local/swift-6.2-RELEASE-wasm-wasi
          sudo mv swift-6.2-RELEASE-wasm-wasi /usr/local/swift-6.2-RELEASE-wasm-wasi
          rm -f swift-toolchain.tar.gz

          TOOLCHAIN_ROOT="/usr/local/swift-6.2-RELEASE-wasm-wasi"
          TOOLCHAIN_PATH="$TOOLCHAIN_ROOT/usr/bin"
          TOOLCHAIN_LIB="$TOOLCHAIN_ROOT/usr/lib/swift/linux"
          TOOLCHAIN_LIB_STATIC="$TOOLCHAIN_ROOT/usr/lib/swift_static/wasi"

          if [ ! -x "$TOOLCHAIN_PATH/swift" ]; then
            echo "Expected Swift binary not found at $TOOLCHAIN_PATH/swift" >&2
            exit 1
          fi

          echo "$TOOLCHAIN_PATH" >> "$GITHUB_PATH"
          COMBINED_LD_LIBRARY_PATH="$TOOLCHAIN_LIB"
          if [ -d "$TOOLCHAIN_LIB_STATIC" ]; then
            COMBINED_LD_LIBRARY_PATH="$TOOLCHAIN_LIB_STATIC:$COMBINED_LD_LIBRARY_PATH"
          fi
          if [ -n "${LD_LIBRARY_PATH:-}" ]; then
            COMBINED_LD_LIBRARY_PATH="$COMBINED_LD_LIBRARY_PATH:${LD_LIBRARY_PATH}"
          fi
          echo "LD_LIBRARY_PATH=$COMBINED_LD_LIBRARY_PATH" >> "$GITHUB_ENV"

          SYSROOT_CANDIDATES=(
            "$TOOLCHAIN_ROOT/share/wasi-sysroot"
            "$TOOLCHAIN_ROOT/usr/share/wasi-sysroot"
            "$TOOLCHAIN_ROOT/share/wasi-sdk/share/wasi-sysroot"
            "$TOOLCHAIN_ROOT/usr/share/wasi-sdk/share/wasi-sysroot"
          )
          WASI_SYSROOT=""
          for candidate in "${SYSROOT_CANDIDATES[@]}"; do
            if [ -d "$candidate" ]; then
              WASI_SYSROOT="$candidate"
              break
            fi
          done
          if [ -z "$WASI_SYSROOT" ]; then
            echo "Unable to locate WASI sysroot within toolchain." >&2
            find "$TOOLCHAIN_ROOT" -maxdepth 4 -type d -name "wasi-sysroot" >&2 || true
            exit 1
          fi
          echo "WASI_SYSROOT=$WASI_SYSROOT" >> "$GITHUB_ENV"

          DESTINATION_FILE="$RUNNER_TEMP/wasi-destination.json"
          cat > "$DESTINATION_FILE" <<EOF
{
  "version": 1,
  "target": "wasm32-unknown-wasi",
  "toolchain-bin-dir": "$TOOLCHAIN_PATH",
  "sdk": "$WASI_SYSROOT"
}
EOF
          echo "WASI_DESTINATION=$DESTINATION_FILE" >> "$GITHUB_ENV"

      - name: Verify Swift 6.2
        shell: bash
        run: |
          set -euo pipefail
          TOOLCHAIN_ROOT="/usr/local/swift-6.2-RELEASE-wasm-wasi"
          TOOLCHAIN_PATH="$TOOLCHAIN_ROOT/usr/bin"
          TOOLCHAIN_LIB="$TOOLCHAIN_ROOT/usr/lib/swift/linux"
          TOOLCHAIN_LIB_STATIC="$TOOLCHAIN_ROOT/usr/lib/swift_static/wasi"
          if [ -d "$TOOLCHAIN_PATH" ]; then
            export PATH="$TOOLCHAIN_PATH:$PATH"
          fi
          COMBINED_LD_LIBRARY_PATH="$TOOLCHAIN_LIB"
          if [ -d "$TOOLCHAIN_LIB_STATIC" ]; then
            COMBINED_LD_LIBRARY_PATH="$TOOLCHAIN_LIB_STATIC:$COMBINED_LD_LIBRARY_PATH"
          fi
          if [ -n "${LD_LIBRARY_PATH:-}" ]; then
            COMBINED_LD_LIBRARY_PATH="$COMBINED_LD_LIBRARY_PATH:${LD_LIBRARY_PATH}"
          fi
          export LD_LIBRARY_PATH="$COMBINED_LD_LIBRARY_PATH"
          swift --version
          swift --version | grep -q "6\.2"

      - name: Build (WASI target)
        shell: bash
        run: |
          set -euo pipefail
          TOOLCHAIN_ROOT="/usr/local/swift-6.2-RELEASE-wasm-wasi"
          TOOLCHAIN_PATH="$TOOLCHAIN_ROOT/usr/bin"
          TOOLCHAIN_LIB="$TOOLCHAIN_ROOT/usr/lib/swift/linux"
          TOOLCHAIN_LIB_STATIC="$TOOLCHAIN_ROOT/usr/lib/swift_static/wasi"
          if [ -d "$TOOLCHAIN_PATH" ]; then
            export PATH="$TOOLCHAIN_PATH:$PATH"
          fi
          COMBINED_LD_LIBRARY_PATH="$TOOLCHAIN_LIB"
          if [ -d "$TOOLCHAIN_LIB_STATIC" ]; then
            COMBINED_LD_LIBRARY_PATH="$TOOLCHAIN_LIB_STATIC:$COMBINED_LD_LIBRARY_PATH"
          fi
          if [ -n "${LD_LIBRARY_PATH:-}" ]; then
            COMBINED_LD_LIBRARY_PATH="$COMBINED_LD_LIBRARY_PATH:${LD_LIBRARY_PATH}"
          fi
          export LD_LIBRARY_PATH="$COMBINED_LD_LIBRARY_PATH"
          if [ -z "${WASI_DESTINATION:-}" ]; then
            echo "WASI_DESTINATION env var missing." >&2
            exit 1
          fi
          swift build --destination "$WASI_DESTINATION"
