name: Windows
on: { push: { branches: [main] }, pull_request: {}, workflow_dispatch: {} }

permissions:
  contents: read

concurrency:
  group: ci-${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2025]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: "6.2.3"
          development: true

      - shell: pwsh
        run: swift build -c release

      - shell: pwsh
        run: swift test
