name: Ensure Swift Version
description: Validate minimum Swift version and install target if needed
inputs:
  min-version:
    required: true
    default: "6.1.2"
  target-version:
    required: true
    default: "6.2.3"
runs:
  using: composite
  steps:
    - id: gate
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          const min = core.getInput('min-version');
          let current = '0.0.0';
          try {
            const out = execSync('swift --version', { encoding: 'utf8' });
            const m = out.match(/Swift version (\d+\.\d+(?:\.\d+)?)/);
            if (m) current = m[1];
          } catch {}
          const toArr = (v) => v.split('.').map(n => parseInt(n, 10));
          const cmp = (a,b) => {
            const aa = toArr(a), bb = toArr(b), n = Math.max(aa.length, bb.length);
            for (let i=0;i<n;i++) {
              const x = aa[i] ?? 0, y = bb[i] ?? 0;
              if (x !== y) return x - y;
            }
            return 0;
          };
          core.setOutput('needs-setup', cmp(current, min) < 0 ? 'true' : 'false');
    - if: steps.gate.outputs.needs-setup == 'true'
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ inputs.target-version }}
    - shell: bash
      run: swift --version
